Header header #Header for message type
bool leg_velocity_mode #Modes
bool mecanum_movement_mode #
bool stabilisize_base_link_mode #
bool stabilisize_ignore_front #
bool stabilisize_ignore_back #
float64 robot_x #robot front movement Basic movement commands
float64 robot_y #robot side movement
float64 robot_zrot #robot z rotation
float64 left_front_leg #front arm angle or up/down movement 
float64 left_back_leg #back arm angle or up/down movement
float64 right_front_leg #front arm angle or up/down movement 
float64 right_back_leg #back arm angle or up/down movement














