Header header #Header for message type
float64 left_wheel # velosity
float64 right_wheel # velosity
float64 base_to_left_front_leg # angle
float64 base_to_left_back_leg # angle
float64 base_to_right_front_leg # angle
float64 base_to_right_back_leg # angle
float64 wheel_to_left_front_leg # velosity
float64 wheel_to_left_back_leg # velosity
float64 wheel_to_right_front_leg # velosity
float64 wheel_to_right_back_leg # velosity
